export const typography =
{
  'fontFamily': 'DM Serif Display',
  'htmlFontSize': 10,
  'h1': {
    'fontFamily': 'DM Serif Display',
    'fontSize': '5.6rem !important',
    'fontWeight': 300,
    'fontStretch': 'normal',
    'fontStyle': 'normal',
    'lineHeight': 1.21428571429,
    'letterSpacing': 'normal',
  },
  'h2': {
    'fontFamily': 'DM Serif Display',
    'fontSize': '4.8rem !important',
    'fontWeight': 300,
    'fontStretch': 'normal',
    'fontStyle': 'normal',
    'lineHeight': 1.20833333333,
    'letterSpacing': '0.01px',
  },
  'h3': {
    'fontFamily': 'Azeret Mono',
    'fontSize': '2.4rem !important',
    'fontWeight': 'bold',
    'fontStretch': 'normal',
    'fontStyle': 'normal',
    'lineHeight': 1.33,
    'letterSpacing': '0.01px',
  },
  'h4': {
    'fontFamily': 'DM Serif Display',
    'fontSize': '3.2rem !important',
    'fontWeight': 'bold',
    'fontStretch': 'normal',
    'fontStyle': 'normal',
    'lineHeight': 1.21875,
    'letterSpacing': '0.01px',
  },
  'h5': {
    // 'fontFamily': 'DM Serif Display',
    // 'fontSize': '2.4rem !important',
    // 'fontWeight': 'bold',
    // 'fontStretch': 'normal',
    // 'fontStyle': 'normal',
    // 'lineHeight': 1.20833333333,
    // 'letterSpacing': '0.01px',
    // 'textAlign': 'left',
  },
  'h6': {
    'fontFamily': 'DM Serif Display',
    'fontSize': '1.6rem !important',
    'fontWeight': 'bold',
    'fontStretch': 'normal',
    'fontStyle': 'normal',
    'lineHeight': 1.1875,
    'letterSpacing': 'normal',
  },
  'subtitle1': {
    // 'fontFamily': 'Fira Sans',
    // 'fontSize': '1.2rem !important',
    // 'fontWeight': 'bold',
    // 'fontStretch': 'normal',
    // 'fontStyle': 'normal',
    // 'lineHeight': 1.16666666667,
    // 'letterSpacing': '0.01px',
    // 'textTransform': 'uppercase',
  },
  'subtitle2': {
    'fontFamily': 'Azeret Mono',
    'fontSize': '1.2rem !important',
    'fontWeight': 'bold',
    'fontStretch': 'normal',
    'fontStyle': 'normal',
    'lineHeight': 1.17,
    'letterSpacing': '0px',
  },
  'body1': {
    // 'fontFamily': 'Fira Sans',
    // 'fontSize': '1.6rem !important',
    // 'fontWeight': 'normal',
    // 'fontStretch': 'normal',
    // 'fontStyle': 'normal',
    // 'lineHeight': 1.1875,
    // 'letterSpacing': '0px',
  },
  'body2': {
    // 'fontFamily': 'Fira Sans',
    // 'fontSize': '1.4rem !important',
    // 'fontWeight': 'normal',
    // 'fontStretch': 'normal',
    // 'fontStyle': 'normal',
    // 'lineHeight': 1.21428571429,
    // 'letterSpacing': '0.01px',
  },
  'button': {
    // 'fontFamily': 'Fira Sans',
    'fontSize': '1.2rem !important',
    // 'fontWeight': 'bold',
    // 'fontStretch': 'normal',
    // 'fontStyle': 'normal',
    // 'lineHeight': 1.21428571429,
    // 'letterSpacing': '0.01px',
    'textTransform': 'none'
  },
  'caption': {
    // 'fontFamily': 'Fira Sans',
    // 'fontSize': '1.2rem !important',
    // 'fontWeight': 'normal',
    // 'fontStretch': 'normal',
    // 'fontStyle': 'normal',
    // 'lineHeight': 1.16666666667,
    // 'letterSpacing': 'normal',
  },
  'overline': {
    // 'fontFamily': 'Fira Sans',
    // 'fontSize': '1rem !important',
    // 'fontWeight': 'bold',
    // 'fontStretch': 'normal',
    // 'fontStyle': 'normal',
    // 'lineHeight': 1.2,
    // 'letterSpacing': 'normal',
  },
};